server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: CONTACT_SERVICE
          uri: lb://CONTACT_SERVICE
          predicates:
            - Path=/contact/**
        - id: contact
          uri: lb://contact
          predicates:
            - Path=/contactus/**